---
title: "OC_CAF_Crosstalk"
output: html_document
date: "2024-05-21"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Package Installation
```{r, eval=FALSE}
# install.packages("devtools")
devtools::install_github("immunogenomics/presto")
devtools::install_github("jinworks/CellChat")
```

## Load Packages
```{r}
library(Seurat)
library(CellChat)
library(ggplot2)
```


## Load Data
```{r}
load("~/Desktop/Lab/Projects/OC_CAF_Crosstalk/Secreted_Signalingin_house_Object.RData")
load("~/Desktop/Lab/Projects/OC_CAF_Crosstalk/Secreted_Signaling_Object.RData")
cellchat@meta$labels[cellchat@meta$labels == "Epithelial_cells"] <- "OC_cells"
cellchat@meta$labels[cellchat@meta$labels == "Smooth_muscle_cells"] <- "CAFs"
table(cellchat@idents)
cellchat <- setIdent(cellchat, ident.use = "labels")
```
## Run CellChat
```{r}
ptm = Sys.time()
cellchat <- computeCommunProb(cellchat, type = "triMean")
cellchat <- filterCommunication(cellchat, min.cells = 10)
cellchat <- computeCommunProbPathway(cellchat)
```

```{r}
cellchat <- aggregateNet(cellchat)
execution.time = Sys.time() - ptm
print(as.numeric(execution.time, units = "secs"))
```





## Visualization
```{r}
# Aggregated Cell-Cell Communication Network (Total Interactions) 
ptm = Sys.time()
groupSize <- as.numeric(table(cellchat@idents))
par(mfrow = c(1,2), xpd=TRUE)
netVisual_circle(cellchat@net$count, vertex.weight = groupSize, weight.scale = T, label.edge= F, title.name = "Number of interactions")
netVisual_circle(cellchat@net$weight, vertex.weight = groupSize, weight.scale = T, label.edge= F, title.name = "Interaction weights/strength")
```


```{r}
# Network Centrality Scores
cellchat <- netAnalysis_computeCentrality(cellchat, slot.name = "netP") 
netAnalysis_signalingRole_network(cellchat, signaling = pathways.show, width = 8, height = 2.5, font.size = 10)
```
```{r}
# Signaling role analysis on the aggregated cell-cell communication network from all signaling pathways
ht1 <- netAnalysis_signalingRole_heatmap(cellchat, pattern = "outgoing")
ht2 <- netAnalysis_signalingRole_heatmap(cellchat, pattern = "incoming")
ht1 + ht2
ht <- netAnalysis_signalingRole_heatmap(cellchat, signaling = c("PDGF", "ncWNT", "WNT"))
ht
```
```{r}
# show all the significant signaling pathways from some cell groups (defined by 'sources.use') to other cell groups (defined by 'targets.use')
netVisual_chord_gene(cellchat, sources.use = c(1:3), targets.use = c(4:13), slot.name = "netP", legend.pos.x = 10, small.gap = 0.2, lab.cex = 0.5)
```


```{r}
pathways.show <- c("PDGF") 
```

### Circle plot
```{r}
par(mfrow=c(1,1))
netVisual_aggregate(cellchat, signaling = pathways.show, layout = "circle")
```
### Chord diagram
```{r}
par(mfrow=c(1,1))
netVisual_aggregate(cellchat, signaling = pathways.show, layout = "chord")
```
### Heatmap
```{r}
par(mfrow=c(1,1))
netVisual_heatmap(cellchat, signaling = pathways.show, color.heatmap = "Reds")
```
### Contribution
```{r}
netAnalysis_contribution(cellchat, signaling = pathways.show)

```
### Single L-R pair
```{r}
pairLR.PDGF <- extractEnrichedLR(cellchat, signaling = pathways.show, geneLR.return = FALSE)
LR.show <- pairLR.PDGF[4,] # show one ligand-receptor pair
```

```{r}
# Chord plot
netVisual_individual(cellchat, signaling = pathways.show,  pairLR.use = LR.show, layout = "chord")
# Circle plot
#netVisual_individual(cellchat, signaling = pathways.show, pairLR.use = LR.show, layout = "circle")
```
```{r}
netVisual_bubble(cellchat, sources.use = c(4:13), targets.use = c(1:3), signaling = c("PDGF"), remove.isolate = FALSE, sort.by.target = TRUE)
netVisual_bubble(cellchat, sources.use = c(1:3), targets.use = c(4:13), signaling = c("PDGF"), remove.isolate = FALSE)
netVisual_bubble(cellchat, sources.use = c(1:3), targets.use = c(4:13), signaling = c("ncWNT"), remove.isolate = FALSE)
```
```{r}
netVisual_chord_gene(cellchat, sources.use = c(4:13), targets.use = c(1:3), signaling = c("PDGF"),legend.pos.x = 8)
netVisual_chord_gene(cellchat, sources.use = c(1:3), targets.use = c(4:13), signaling = c("ncWNT"),legend.pos.x = 8, small.gap = 0.1)

```


